### ISSUE TITLE
[DESIGN] The page title breaks on the `about` page

### ISSUE THREAD

**Issue by AntoniosBarotsis** [Zakrok09/RoTUer#25]
## How to Reproduce

Navigating to the `/about` page switches the website's title from `RoTUer` to `About | RoTUer` which persists even when navigating back to other parts of the website.

## Possible Solutions

[These](https://github.com/Zakrok09/RoTUer/blob/1d0028f4771e2dda835c980ee8a67b0538e97fee/src/routes/about/%2Bpage.svelte#L10-L13) lines could be removed. Alternatively, [this thread](https://github.com/sveltejs/kit/issues/3305) might help.

This is the most minute thing but since I saw it, thought I'd mention it 👍 Nice work on the project so far!

**Comment by Zakrok09** [comment]
This is the perfect time to submit the issue! I am working on it.
Now final changes are being implemented and the initial release should be published tomorrow.

**Comment by Zakrok09** [comment]
Thank you so much for the issue submission!
