### ISSUE TITLE
[IMPROVEMENT] Translate tags to Dutch as well

### ISSUE THREAD

**Issue by ThijsH04** [Zakrok09/RoTUer#31]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Zakrok09** [comment]
I would consider this a localization improvement.

Also I think it will be worked on a later stage because currently the algorithm only works with English names and it isn't much of a burden.

**Comment by Zakrok09** [comment]
@ThijsH04 fixed this issue by himself

what a legend!
